name: taxadb2_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - setuptools>=67.6.0
  - requests
  - peewee>=3.8.2
  - tqdm
  - psycopg2>=2.6.2
  - PyMySQL>=0.7.10
  - pytest
  - pip
