name: taxadb2_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.13
  - setuptools>=67.5.1
  - requests
  - peewee>=3.8.2
  - tqdm
  - pip
  - pip:
      - ipykernel
      - nbsphinx
      - sphinx-rtd-theme
