name: taxadb2_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - setuptools>=67.5.1
  - requests
  - peewee>=3.8.2
  - tqdm
  - pytest
  - pip
  - pip:
      - ipykernel
      - nbsphinx
      - myst-nb
      - sphinx-rtd-theme
